name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmmss
          utcOffset: "+08:00"

      - name: Setup Environment
        run: |
          sudo apt-fast update
          sudo apt-fast -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
      
      - uses: actions/cache@v2
        id: cache
        with:
          path: lede
          key: ${{ runner.os }}-openwrt
          restore-keys: |
            ${{ runner.os }}-openwrt

      - name: Setup OpenWRT SDK
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          git clone https://github.com/Zxilly/UA2F.git package/UA2F
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          rm -f ./.config*
          touch ./.config
          
          cat >> .config <<EOF
          CONFIG_TARGET_ipq60xx=y
          CONFIG_TARGET_ipq60xx_generic=y
          CONFIG_TARGET_ipq60xx_generic_Default=y
          
          CONFIG_PACKAGE_ua2f=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-filter=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_iptables-mod-nfqueue=y			   
          CONFIG_PACKAGE_iptables-mod-u32=y

          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-filter=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-nfqueue=y			   
          CONFIG_PACKAGE_kmod-ipt-u32=y
          CONFIG_PACKAGE_kmod-nfnetlink-queue=y

          CONFIG_LUCI_LANG_zh_Hans=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-app-argon-config=y
          
          CONFIG_NETFILTER_NETLINK_GLUE_CT=y
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: lede/package/UA2F

      - name: Compile Package
        working-directory: ./lede
        run: |
          make defconfig
          make download -j$(nproc) V=s
          make package/UA2F/compile -j2 V=s

      - name: Release Package
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.current-time.outputs.formattedTime }}"
          prerelease: true
          files: |
            lede/bin/packages/arm_cortex-a7_neon-vfpv4/base/ua2f*




